language: cpp
compiler:
  - gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-filesystem1.55-dev
      - libboost-regex1.55-dev
      - libboost-date-time1.55-dev
      - libboost-thread1.55-dev
      - libboost-log1.55-dev
      - libboost-locale1.55-dev
      - libboost-chrono1.55-dev
      - libboost-random1.55-dev
  coverity_scan:
    project:
      name: "puppetlabs/pxp-agent"
      description: "Build submitted via Travis CI"
    notification_email: michael.smith@puppetlabs.com
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8 --template && $USERDIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$USERDIR -DLEATHERMAN_GETTEXT=OFF ."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  # Use a predefined install location; cppcheck requires the cfg location is defined at compile-time.
  - mkdir -p $USERDIR
  # grab a pre-built cmake 3.2.3
  - wget https://s3.amazonaws.com/kylo-pl-bucket/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz --strip 1 -C $USERDIR
  # Install pxp-agent's dependencies
  - wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz
  - tar xzvf leatherman.tar.gz -C $USERDIR
  - wget https://github.com/puppetlabs/cpp-pcp-client/releases/download/${CPP_PCP_CLIENT_VERSION}/cpp-pcp-client.tar.gz
  - tar xzvf cpp-pcp-client.tar.gz -C $USERDIR
  # For some reason this link is missing, need to fix it upstream.
  - ln -s $USERDIR/lib/libcpp-pcp-client.so.1.5.4 $USERDIR/lib/libcpp-pcp-client.so
  - rvm install 2.1.9
  - export CC=gcc-4.8 CXX=g++-4.8

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./.travis_target.sh ; fi

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "KucDHNeQ/WAwcYZgA/YJNNRai1BYv2YoRmYIOUoZztlGNvXL5mptXIGB4o3SELwgIjXaoljdLusIV5Uu8SNNrvXqGkbboa0fp38XwzntpZic6tEBvkpBdC13R6iNlCMwobKqUQXJ+PWg0UGnb6lI9iqdZgdWtKTxR+6aHNCh2uG+MHH6NiuYktA+LjBPPR24y7JWRqbfT8YL8d3galNS1smFYp4hUyb7ieeSIXcC1lg85TSHlwEblCItT39vdts2g0OD2Untjbk3hzBG2tH5S2nShvXwcWtuqy5WvkDWCwD4O24PMU1Mlgz0W/DqonekDPB7kpXaWHPltct76oSLL6xVm9Xg2YLxCHQ608RLHzQ3AWYfHSvT5ZiCNcu50h0HTE4DH+z8E5rAKUw5c00OOuGklZfiLyr0Le3fx6g3jFBVwFeiq+HpeY5bHSDIRTJZ+8XyozIcSSQa0/hZDSO2ELJHCqFctLKGo2tPFV9FqvC1oYg4cQodt3VkJErVDXXIRF9Dcw6kx1MLgRPNnxTF2jCSswmWVtG+60wW5jJk7wwFQHV3DHbosmHQZRZ7cVcrZA3p31QSAvb59lT7EkcuKEWwMekirPI6Mq38LPLtE8MM7H+NAIzmeaoOizqPupHn8/CY5hvjievMESJQbLO6fKn+1vMI41S/PJHHLlyWzCQ="
    - USERDIR=/tmp/userdir
    - PYTHONUSERBASE=$USERDIR
    - PATH=$USERDIR/bin:$PATH
    - LD_LIBRARY_PATH=$USERDIR/lib:$LD_LIBRARY_PATH
    - LEATHERMAN_VERSION=1.2.1
    - CPP_PCP_CLIENT_VERSION=1.5.4

notifications:
  email: false

