language: cpp
compiler:
  - gcc
sudo: false
ruby: '2.1.9'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-filesystem1.55-dev
      - libboost-regex1.55-dev
      - libboost-date-time1.55-dev
      - libboost-thread1.55-dev
      - libboost-log1.55-dev
      - libboost-locale1.55-dev
      - libboost-chrono1.55-dev
      - libboost-random1.55-dev
  coverity_scan:
    project:
      name: "puppetlabs/pxp-agent"
      description: "Build submitted via Travis CI"
    notification_email: michael.smith@puppetlabs.com
    build_command_prepend: "cov-configure --comptype gcc --compiler gcc-4.8 --template && $USERDIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$USERDIR -DLEATHERMAN_GETTEXT=OFF ."
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  # Use a predefined install location; cppcheck requires the cfg location is defined at compile-time.
  - mkdir -p $USERDIR
  # grab a pre-built cmake 3.2.3
  - wget https://s3.amazonaws.com/kylo-pl-bucket/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz --strip 1 -C $USERDIR
  # Install pxp-agent's dependencies
  - wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz
  - tar xzvf leatherman.tar.gz -C $USERDIR
  - rvm install 2.1.9
  - export CC=gcc-4.8 CXX=g++-4.8

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./.travis_target.sh ; fi

env:
  global:
    - USERDIR=/tmp/userdir
    - PYTHONUSERBASE=$USERDIR
    - PATH=$USERDIR/bin:$PATH
    - LD_LIBRARY_PATH=$USERDIR/lib:$LD_LIBRARY_PATH
    - LEATHERMAN_VERSION=0.11.0
    - CPP_PCP_CLIENT_VERSION=master

notifications:
  email: false

